# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\f0kes\Desktop\ACCR\QtGui\QtGui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import timeit
import re
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(573, 482)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pb_UPChange = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pb_UPChange.setFont(font)
        self.pb_UPChange.setObjectName("pb_UPChange")
        self.gridLayout_3.addWidget(self.pb_UPChange, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.tb_UPTable = QtWidgets.QListWidget(self.centralWidget)
        self.tb_UPTable.setObjectName("tb_UPTable")
        self.gridLayout_3.addWidget(self.tb_UPTable, 1, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 2, 2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.pb_MTOChange = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pb_MTOChange.setFont(font)
        self.pb_MTOChange.setObjectName("pb_MTOChange")
        self.gridLayout_5.addWidget(self.pb_MTOChange, 0, 1, 1, 1)
        self.tb_MTOTable = QtWidgets.QListWidget(self.centralWidget)
        self.tb_MTOTable.setObjectName("tb_MTOTable")
        self.gridLayout_5.addWidget(self.tb_MTOTable, 1, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_5, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(389, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 2)
        self.pb_Group = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pb_Group.setFont(font)
        self.pb_Group.setObjectName("pb_Group")
        self.gridLayout.addWidget(self.pb_Group, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.pb_KOChange = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pb_KOChange.setFont(font)
        self.pb_KOChange.setObjectName("pb_KOChange")
        self.gridLayout_4.addWidget(self.pb_KOChange, 0, 1, 1, 1)
        self.tb_KOTable = QtWidgets.QListWidget(self.centralWidget)
        self.tb_KOTable.setObjectName("tb_KOTable")
        self.gridLayout_4.addWidget(self.tb_KOTable, 1, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_4, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 573, 21))
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setWindowTitle("")
        self.mainToolBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_SaveAs = QtWidgets.QAction(MainWindow)
        self.action_SaveAs.setObjectName("action_SaveAs")
        self.action_MTOPDF = QtWidgets.QAction(MainWindow)
        self.action_MTOPDF.setObjectName("action_MTOPDF")
        self.action_MTODOCX = QtWidgets.QAction(MainWindow)
        self.action_MTODOCX.setObjectName("action_MTODOCX")
        self.action_KOPDF = QtWidgets.QAction(MainWindow)
        self.action_KOPDF.setObjectName("action_KOPDF")
        self.action_KODOCX = QtWidgets.QAction(MainWindow)
        self.action_KODOCX.setObjectName("action_KODOCX")
        self.action_PPS = QtWidgets.QAction(MainWindow)
        self.action_PPS.setObjectName("action_PPS")
        self.action_UP = QtWidgets.QAction(MainWindow)
        self.action_UP.setObjectName("action_UP")
        self.action_GN = QtWidgets.QAction(MainWindow)
        self.action_GN.setObjectName("action_GN")
        self.action_KOFormul = QtWidgets.QAction(MainWindow)
        self.action_KOFormul.setObjectName("action_KOFormul")
        self.action_TemplateMTO = QtWidgets.QAction(MainWindow)
        self.action_TemplateMTO.setObjectName("action_TemplateMTO")
        self.action_TemplateKO = QtWidgets.QAction(MainWindow)
        self.action_TemplateKO.setObjectName("action_TemplateKO")
        self.action_AudienceFilling = QtWidgets.QAction(MainWindow)
        self.action_AudienceFilling.setObjectName("action_AudienceFilling")
        self.action_KOFilling = QtWidgets.QAction(MainWindow)
        self.action_KOFilling.setObjectName("action_KOFilling")
        self.action_CheckPercent = QtWidgets.QAction(MainWindow)
        self.action_CheckPercent.setObjectName("action_CheckPercent")
        self.action_Audience = QtWidgets.QAction(MainWindow)
        self.action_Audience.setObjectName("action_Audience")
        self.menu.addAction(self.action_Open)
        self.menu.addAction(self.action_Save)
        self.menu.addAction(self.action_SaveAs)
        self.menu_2.addAction(self.action_MTOPDF)
        self.menu_2.addAction(self.action_MTODOCX)
        self.menu_2.addAction(self.action_KOPDF)
        self.menu_2.addAction(self.action_KODOCX)
        self.menu_3.addAction(self.action_Audience)
        self.menu_3.addAction(self.action_PPS)
        self.menu_3.addAction(self.action_UP)
        self.menu_3.addAction(self.action_GN)
        self.menu_3.addAction(self.action_KOFormul)
        self.menu_4.addAction(self.action_TemplateMTO)
        self.menu_4.addAction(self.action_TemplateKO)
        self.menu_5.addAction(self.action_AudienceFilling)
        self.menu_5.addAction(self.action_KOFilling)
        self.menu_5.addAction(self.action_CheckPercent)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pb_Group, self.tb_UPTable)
        MainWindow.setTabOrder(self.tb_UPTable, self.pb_UPChange)
        MainWindow.setTabOrder(self.pb_UPChange, self.tb_KOTable)
        MainWindow.setTabOrder(self.tb_KOTable, self.pb_KOChange)
        MainWindow.setTabOrder(self.pb_KOChange, self.tb_MTOTable)
        MainWindow.setTabOrder(self.tb_MTOTable, self.pb_MTOChange)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QtGui"))
        self.pb_UPChange.setText(_translate("MainWindow", "Редактировать"))
        self.label.setText(_translate("MainWindow", "УП"))
        self.label_3.setText(_translate("MainWindow", "МТО"))
        self.pb_MTOChange.setText(_translate("MainWindow", "Редактировать"))
        self.pb_Group.setText(_translate("MainWindow", "Выбор группы"))
        self.label_2.setText(_translate("MainWindow", "Кадры"))
        self.pb_KOChange.setText(_translate("MainWindow", "Редактировать"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Сгенерировать справку"))
        self.menu_3.setTitle(_translate("MainWindow", "Справочники"))
        self.menu_4.setTitle(_translate("MainWindow", "Шаблон"))
        self.menu_5.setTitle(_translate("MainWindow", "Проверка"))
        self.action_Open.setText(_translate("MainWindow", "Открыть"))
        self.action_Save.setText(_translate("MainWindow", "Сохранить"))
        self.action_SaveAs.setText(_translate("MainWindow", "Сохранить как..."))
        self.action_MTOPDF.setText(_translate("MainWindow", "МТО PDF"))
        self.action_MTODOCX.setText(_translate("MainWindow", "МТО DOCX"))
        self.action_KOPDF.setText(_translate("MainWindow", "КО PDF"))
        self.action_KODOCX.setText(_translate("MainWindow", "КО DOCX"))
        self.action_PPS.setText(_translate("MainWindow", "Справочник ППС"))
        self.action_UP.setText(_translate("MainWindow", "Справочник УП"))
        self.action_GN.setText(_translate("MainWindow", "Справочник Г.Н."))
        self.action_KOFormul.setText(_translate("MainWindow", "Справочник КО формул"))
        self.action_TemplateMTO.setText(_translate("MainWindow", "Загрузить шаблон МТО"))
        self.action_TemplateKO.setText(_translate("MainWindow", "Загрузить шаблон КО"))
        self.action_AudienceFilling.setText(_translate("MainWindow", "Заполнены аудитории"))
        self.action_KOFilling.setText(_translate("MainWindow", "Заполнены кадры"))
        self.action_CheckPercent.setText(_translate("MainWindow", "Проверка %"))
        self.action_Audience.setText(_translate("MainWindow", "Справочник аудиторий"))
        
    